# compiled from and inspired by:
# https://eslint.org/docs/rules
# https://github.com/google/eslint-config-google
# https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app
# https://github.com/benmosher/eslint-plugin-import
# https://github.com/evcohen/eslint-plugin-jsx-a11y

# specify a parser that can understand all the cutting-edge JavaScript features/syntaxes we want to use
# https://eslint.org/docs/user-guide/configuring#specifying-parser
parser: babel-eslint

# set the parser to recognize all the cutting-edge JavaScript features/syntaxes we want to use
# https://eslint.org/docs/user-guide/configuring#specifying-parser-options
parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true

# specify environments to define global variables
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true
  node: true
  commonjs: true
  es2020: true
  worker: true
  amd: true
  jest: true

# specify plugins to provide more rules and allow linting in additional contexts
plugins:
- import
- html
- react 
- react-hooks
- jsx-a11y

# full rule set that we want to test and auto-fix for
rules:
  # CORE - Possible Errors
  for-direction:
  - off
  getter-return:
  - off
  no-async-promise-executor:
  - off
  no-await-in-loop:
  - off
  no-compare-neg-zero:
  - warn
  no-cond-assign:
  - warn
  no-console:
  - off
  no-constant-condition:
  - warn
  no-control-regex:
  - warn
  no-debugger:
  - off
  no-dupe-args:
  - warn
  no-dupe-else-if:
  - warn
  no-dupe-keys:
  - warn
  no-duplicate-case:
  - warn
  no-empty:
  - warn
  no-empty-character-class:
  - warn
  no-ex-assign:
  - warn
  no-extra-boolean-cast:
  - warn
  no-extra-parens:
  - off
  no-extra-semi:
  - warn
  no-func-assign:
  - warn
  no-import-assign:
  - warn
  no-inner-declarations:
  - off
  no-invalid-regexp:
  - warn
  no-irregular-whitespace:
  - warn
  no-misleading-character-class:
  - off
  no-obj-calls:
  - warn
  no-prototype-builtins:
  - off
  no-regex-spaces:
  - off
  no-setter-return:
  - off
  no-sparse-arrays:
  - warn
  no-template-curly-in-string:
  - warn
  no-unexpected-multiline:
  - warn
  no-unreachable:
  - warn
  no-unsafe-finally:
  - warn
  no-unsafe-negation:
  - warn
  no-useless-backreference:
  - off
  require-atomic-updates:
  - off
  use-isnan:
  - warn
  valid-typeof:
  - warn

  # CORE - Best Practices
  accessor-pairs:
  - off
  array-callback-return:
  - off
  block-scoped-var:
  - warn
  class-methods-use-this:
  - warn
  complexity:
  - off
  consistent-return:
  - off
  curly:
  - warn
  - multi-or-nest
  default-case:
  - warn
  default-case-last:
  - off
  default-param-last:
  - off
  dot-location:
  - warn
  - property
  dot-notation:
  - warn
  eqeqeq:
  - warn
  grouped-accessor-pairs:
  - off
  guard-for-in:
  - warn
  max-classes-per-file:
  - off
  no-alert:
  - off
  no-caller:
  - warn
  no-case-declarations:
  - warn
  no-constructor-return:
  - warn
  no-div-regex:
  - off
  no-else-return:
  - off
  no-empty-function:
  - off
  no-empty-pattern:
  - warn
  no-eq-null:
  - warn
  no-eval:
  - warn
  no-extend-native:
  - warn
  no-extra-bind:
  - warn
  no-extra-label:
  - warn
  no-fallthrough:
  - warn
  no-floating-decimal:
  - warn
  no-global-assign:
  - warn
  no-implicit-coercion:
  - warn
  no-implicit-globals:
  - off
  no-implied-eval:
  - warn
  no-invalid-this:
  - warn
  no-iterator:
  - warn
  no-labels:
  - warn
  no-lone-blocks:
  - warn
  no-loop-func:
  - warn
  no-magic-numbers:
  - off
  no-multi-spaces:
  - warn
  no-multi-str:
  - warn
  no-new:
  - warn
  no-new-func:
  - warn
  no-new-wrappers:
  - warn
  no-octal:
  - warn
  no-octal-escape:
  - off
  no-param-reassign:
  - off
  no-proto:
  - warn
  no-redeclare:
  - warn
  no-restricted-properties:
  - off
  no-return-assign:
  - off
  no-return-await:
  - warn
  no-script-url:
  - warn
  no-self-assign:
  - warn
  no-self-compare:
  - warn
  no-sequences:
  - off
  no-throw-literal:
  - warn
  no-unmodified-loop-condition:
  - off
  no-unused-expressions:
  - off
  no-unused-labels:
  - warn
  no-useless-call:
  - warn
  no-useless-catch:
  - warn
  no-useless-concat:
  - warn
  no-useless-escape:
  - warn
  no-useless-return:
  - off
  no-void:
  - warn
  no-warn-comments:
  - off
  no-with:
  - warn
  prefer-named-capture-group:
  - off
  prefer-promise-reject-errors:
  - warn
  prefer-regex-literals:
  - off
  radix:
  - off
  require-await:
  - warn
  require-unicode-regexp:
  - off
  vars-on-top:
  - off
  wrap-iife:
  - warn
  yoda:
  - warn

  # CORE - Strict Mode
  strict:
  - off

  # CORE - Variables
  init-declarations:
  - off
  no-delete-var:
  - warn
  no-label-var:
  - warn
  no-restricted-globals:
  - warn
  no-shadow:
  - off
  no-shadow-restricted-names:
  - warn
  no-undef:
  - warn
  no-undef-init:
  - off
  no-undefined:
  - off
  no-unused-vars:
  - warn
  no-use-before-define:
  - warn
  - functions: false
    classes: false
    variables: false

  # CORE - Node.js and CommonJS
  callback-return:
  - off
  global-require:
  - off
  handle-callback-err:
  - off
  no-buffer-constructor:
  - off
  no-mixed-requires:
  - off
  no-new-require:
  - off
  no-path-concat:
  - off
  no-process-env:
  - off
  no-process-exit:
  - off
  no-restricted-modules:
  - off
  no-sync:
  - off

  # CORE - Stylistic Issues
  array-bracket-newline:
  - off
  array-bracket-spacing:
  - warn
  array-element-newline:
  - off
  block-spacing:
  - warn
  brace-style:
  - warn
  camelcase:
  - off
  capitalized-comments:
  - off
  comma-dangle:
  - warn
  comma-spacing:
  - warn
  comma-style:
  - warn
  computed-property-spacing:
  - warn
  consistent-this:
  - warn
  eol-last:
  - warn
  func-call-spacing:
  - warn
  func-name-matching:
  - warn
  func-names:
  - warn
  - never
  func-style:
  - off
  function-call-argument-newline:
  - warn
  - consistent
  function-paren-newline:
  - warn
  - multiline-arguments
  id-blacklist:
  - off
  id-length:
  - off
  id-match:
  - off
  implicit-arrow-linebreak:
  - off
  indent:
  - warn
  - 2
  - SwitchCase: 1
    VariableDeclarator: first
    outerIIFEBody: 0
    MemberExpression: 1
    FunctionDeclaration:
      parameters: first
      body: 1
    CallExpression:
      arguments: first
    ArrayExpression: first
    ObjectExpression: first
    ImportDeclaration: first
    flatTernaryExpressions: false
    ignoreComments: false
  jsx-quotes:
  - warn
  - prefer-single
  key-spacing:
  - warn
  keyword-spacing:
  - warn
  line-comment-position:
  - off
  linebreak-style:
  - warn
  lines-around-comment:
  - off
  lines-between-class-members:
  - warn
  max-depth:
  - off
  max-len:
  - warn
  - code: 80
    comments: 80
    tabWidth: 2
    ignorePattern: true
    ignoreComments: true
    ignoreTrailingComments: true
    ignoreUrls: true
    ignoreStrings: true
    ignoreTemplateLiterals: true
    ignoreRegExpLiterals: true
  max-lines:
  - off
  max-lines-per-function:
  - off
  max-nested-callbacks:
  - off
  max-params:
  - off
  max-statements:
  - off
  max-statements-per-line:
  - off
  multiline-comment-style:
  - off
  multiline-ternary:
  - off
  new-cap:
  - warn
  new-parens:
  - warn
  newline-per-chained-call:
  - off
  no-array-constructor:
  - warn
  no-bitwise:
  - off
  no-continue:
  - off
  no-inline-comments:
  - off
  no-lonely-if:
  - off
  no-mixed-operators:
  - off
  no-mixed-spaces-and-tabs:
  - warn
  no-multi-assign:
  - off
  no-multiple-empty-lines:
  - warn
  - max: 2
  no-negated-condition:
  - off
  no-nested-ternary:
  - off
  no-new-object:
  - warn
  no-plusplus:
  - off
  no-restricted-syntax:
  - off
  no-tabs:
  - warn
  no-ternary:
  - off
  no-trailing-spaces:
  - warn
  no-underscore-dangle:
  - off
  no-unneeded-ternary:
  - off
  no-whitespace-before-property:
  - warn
  nonblock-statement-body-position:
  - warn
  - below
  object-curly-newline:
  - warn
  - multiline: true
    consistent: true
  object-curly-spacing:
  - warn
  - always
  object-property-newline:
  - off
  one-var:
  - off
  one-var-declaration-per-line:
  - warn
  - always
  operator-assignment:
  - off
  operator-linebreak:
  - warn
  - after
  padded-blocks:
  - warn
  - never
  padding-line-between-statements:
  - off
  prefer-exponentiation-operator:
  - off
  prefer-object-spread:
  - warn
  quote-props:
  - warn
  - consistent
  quotes:
  - warn
  - single
  - avoidEscape: true
    allowTemplateLiterals: true
  semi:
  - warn
  semi-spacing:
  - warn
  semi-style:
  - warn
  sort-keys:
  - off
  sort-vars:
  - off
  space-before-blocks:
  - warn
  space-before-function-paren:
  - warn
  - named: never
    anonymous: never
    asyncArrow: always
  space-in-parens:
  - warn
  space-infix-ops:
  - warn
  space-unary-ops:
  - off
  spaced-comment:
  - warn
  switch-colon-spacing:
  - warn
  template-tag-spacing:
  - off
  unicode-bom:
  - off
  wrap-regex:
  - off

  # CORE - ECMAScript 6
  arrow-body-style:
  - off
  arrow-parens:
  - warn
  arrow-spacing:
  - warn
  constructor-super:
  - warn
  generator-star-spacing:
  - warn
  no-class-assign:
  - warn
  no-confusing-arrow:
  - off
  no-const-assign:
  - warn
  no-dupe-class-members:
  - warn
  no-duplicate-imports:
  - off
  no-new-symbol:
  - warn
  no-restricted-exports:
  - off
  no-restricted-imports:
  - off
  no-this-before-super:
  - warn
  no-useless-computed-key:
  - warn
  no-useless-constructor:
  - warn
  no-useless-rename:
  - warn
  no-var:
  - warn
  object-shorthand:
  - off
  prefer-arrow-callback:
  - warn
  prefer-const:
  - warn
  - destructuring: all
  prefer-destructuring:
  - off
  prefer-numeric-literals:
  - off
  prefer-rest-params:
  - warn
  prefer-spread:
  - warn
  prefer-template:
  - off
  require-yield:
  - warn
  rest-spread-spacing:
  - warn
  sort-imports:
  - off
  symbol-description:
  - off
  template-curly-spacing:
  - warn
  yield-star-spacing:
  - warn

  # PLUGIN - import
  import/no-unresolved:
  - off
  import/named:
  - off
  import/default:
  - off
  import/namespace:
  - off
  import/no-restricted-paths:
  - off
  import/no-absolute-path:
  - off
  import/no-dynamic-require:
  - off
  import/no-internal-modules:
  - off
  import/no-webpack-loader-syntax:
  - off
  import/no-self-import:
  - off
  import/no-cycle:
  - off
  import/no-useless-path-segments:
  - off
  import/no-relative-parent-imports:
  - off
  import/no-unused-modules:
  - off
  import/export:
  - off
  import/no-named-as-default:
  - off
  import/no-named-as-default-member:
  - off
  import/no-deprecated:
  - off
  import/no-extraneous-dependencies:
  - off
  import/no-mutable-exports:
  - off
  import/unambiguous:
  - off
  import/no-commonjs:
  - off
  import/no-amd:
  - warn
  import/no-nodejs-modules:
  - off
  import/first:
  - warn
  import/exports-last:
  - off
  import/no-duplicates:
  - off
  import/no-namespace:
  - off
  import/extensions:
  - off
  import/order:
  - off
  import/newline-after-import:
  - off
  import/prefer-default-export:
  - off
  import/max-dependencies:
  - off
  import/no-unassigned-import:
  - off
  import/no-named-default:
  - off
  import/no-default-export:
  - off
  import/no-named-export:
  - off
  import/no-anonymous-default-export:
  - off
  import/group-exports:
  - off
  import/dynamic-import-chunkname:
  - off

  # PLUGIN - react
  react/boolean-prop-naming:
  - off
  react/button-has-type:
  - off
  react/default-props-match-prop-types:
  - off
  react/destructuring-assignment:
  - off
  react/display-name:
  - off
  react/forbid-component-props:
  - off
  react/forbid-dom-props:
  - off
  react/forbid-elements:
  - off
  react/forbid-foreign-prop-types:
  - off
  react/forbid-prop-types:
  - off
  react/function-component-definition:
  - off
  react/no-access-state-in-setstate:
  - off
  react/no-adjacent-inline-elements:
  - off
  react/no-array-index-key:
  - off
  react/no-children-prop:
  - warn
  react/no-danger:
  - off
  react/no-danger-with-children:
  - warn
  react/no-deprecated:
  - warn
  react/no-did-mount-set-state:
  - off
  react/no-did-update-set-state:
  - off
  react/no-direct-mutation-state:
  - warn
  react/no-find-dom-node:
  - warn
  react/no-is-mounted:
  - warn
  react/no-multi-comp:
  - off
  react/no-redundant-should-component-update:
  - off
  react/no-render-return-value:
  - warn
  react/no-set-state:
  - off
  react/no-string-refs:
  - warn
  react/no-this-in-sfc:
  - off
  react/no-typos:
  - warn
  react/no-unescaped-entities:
  - off
  react/no-unknown-property:
  - warn
  react/no-unsafe:
  - off
  react/no-unused-prop-types:
  - off
  react/no-unused-state:
  - off
  react/no-will-update-set-state:
  - off
  react/prefer-es6-class:
  - off
  react/prefer-read-only-props:
  - off
  react/prefer-stateless-function:
  - off
  react/prop-types:
  - off
  react/react-in-jsx-scope:
  - warn
  react/require-default-props:
  - off
  react/require-optimization:
  - off
  react/require-render-return:
  - warn
  react/self-closing-comp:
  - off
  react/sort-comp:
  - off
  react/sort-prop-types:
  - off
  react/state-in-constructor:
  - off
  react/static-property-placement:
  - off
  react/style-prop-object:
  - warn
  react/void-dom-elements-no-children:
  - off

  # PLUGIN - react - JSX-specific rules
  react/jsx-boolean-value:
  - off
  react/jsx-child-element-spacing:
  - off
  react/jsx-closing-bracket-location:
  - off
  react/jsx-closing-tag-location:
  - off
  react/jsx-curly-brace-presence:
  - off
  react/jsx-curly-newline:
  - off
  react/jsx-curly-spacing:
  - off
  react/jsx-equals-spacing:
  - off
  react/jsx-filename-extension:
  - warn
  - extensions:
    - .js
    - .jsx
  react/jsx-first-prop-new-line:
  - off
  react/jsx-fragments:
  - off
  react/jsx-handler-names:
  - off
  react/jsx-indent:
  - off
  react/jsx-indent-props:
  - off
  react/jsx-key:
  - warn
  react/jsx-max-depth:
  - off
  react/jsx-max-props-per-line:
  - off
  react/jsx-no-bind:
  - off
  react/jsx-no-comment-textnodes:
  - warn
  react/jsx-no-duplicate-props:
  - warn
  react/jsx-no-literals:
  - off
  react/jsx-no-script-url:
  - off
  react/jsx-no-target-blank:
  - warn
  react/jsx-no-undef:
  - warn
  react/jsx-no-useless-fragment:
  - off
  react/jsx-one-expression-per-line:
  - off
  react/jsx-pascal-case:
  - warn
  react/jsx-props-no-multi-spaces:
  - off
  react/jsx-props-no-spreading:
  - off
  react/jsx-sort-default-props:
  - off
  react/jsx-sort-props:
  - off
  react/jsx-space-before-closing:
  - off
  react/jsx-tag-spacing:
  - off
  react/jsx-uses-react:
  - warn
  react/jsx-uses-vars:
  - warn
  react/jsx-wrap-multilines:
  - off

  # PLUGIN - react-hooks
  react-hooks/rules-of-hooks: 
  - warn
  react-hooks/exhaustive-deps: 
  - warn

  # PLUGIN - jsx-a11ywarn
  jsx-a11y/accessible-emoji:
  - warn
  jsx-a11y/alt-text:
  - warn
  jsx-a11y/anchor-has-content:
  - warn
  jsx-a11y/anchor-is-valid:
  - off
  jsx-a11y/aria-activedescendant-has-tabindex:
  - warn
  jsx-a11y/aria-props:
  - warn
  jsx-a11y/aria-proptypes:
  - warn
  jsx-a11y/aria-role:
  - warn
  jsx-a11y/aria-unsupported-elements:
  - warn
  jsx-a11y/click-events-have-key-events:
  - off
  jsx-a11y/control-has-associated-label:
  - off
  jsx-a11y/heading-has-content:
  - warn
  jsx-a11y/html-has-lang:
  - off
  jsx-a11y/iframe-has-title:
  - warn
  jsx-a11y/img-redundant-alt:
  - warn
  jsx-a11y/interactive-supports-focus:
  - off
  jsx-a11y/label-has-associated-control:
  - off
  jsx-a11y/label-has-for:
  - off
  jsx-a11y/lang:
  - off
  jsx-a11y/media-has-caption:
  - off
  jsx-a11y/mouse-events-have-key-events:
  - off
  jsx-a11y/no-access-key:
  - warn
  jsx-a11y/no-autofocus:
  - off
  jsx-a11y/no-distracting-elements:
  - warn
  jsx-a11y/no-interactive-element-to-noninteractive-role:
  - off
  jsx-a11y/no-noninteractive-element-interactions:
  - off
  jsx-a11y/no-noninteractive-element-to-interactive-role:
  - off
  jsx-a11y/no-noninteractive-tabindex:
  - off
  jsx-a11y/no-onchange:
  - off
  jsx-a11y/no-redundant-roles:
  - warn
  jsx-a11y/no-static-element-interactions:
  - off
  jsx-a11y/role-has-required-aria-props:
  - warn
  jsx-a11y/role-supports-aria-props:
  - warn
  jsx-a11y/scope:
  - warn
  jsx-a11y/tabindex-no-positive:
  - off
